{% set name = "cucopy" %}
{% set version = "1.2.2" %}
{% set pyhon_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cucopy-{{ version }}.tar.gz
  sha256: f93117b08c0be9d146918097522caa0663cf14f20d8019c53361a45fddb77bb4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - setuptools-git
    - pip
  run:
    - python >={{ python_min }}
    - pandas

test:
  imports:
    - cucopy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://jugit.fz-juelich.de/iek-3/groups/data-and-model-integration/cucopy
  summary: The CuCoPy package provides methods for exchanging currencies and adjusting monetary values for inflation until 1960 on a yearly basis.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
